# Adaptive Zsh frontend. Generated by `adaptive init zsh`.
[[ -o interactive ]] || return 0
: ${ADAPTIVE_GHOST_TEXT:=1}
: ${ADAPTIVE_GHOST_STYLE:=fg=245}
: ${ADAPTIVE_MENU:=1}
: ${ADAPTIVE_ENTER_ACCEPTS_MENU:=0}
: ${ADAPTIVE_ACCEPT_KEY:=^I}
: ${ADAPTIVE_MENU_NEXT_KEY:=^[[C}
typeset -g ADAPTIVE_QUERY_FD="" ADAPTIVE_QUERY_PID="" ADAPTIVE_PREFIX_LEN=0 ADAPTIVE_MENU_INDEX=1 ADAPTIVE_GHOST_HIGHLIGHT=""
typeset -ga ADAPTIVE_VALUES ADAPTIVE_LABELS ADAPTIVE_DESCRIPTIONS ADAPTIVE_SOURCES region_highlight

_adaptive_clear_ghost() {
  POSTDISPLAY=""
  if [[ -n "$ADAPTIVE_GHOST_HIGHLIGHT" ]]; then
    local -a kept; local highlight
    for highlight in "${region_highlight[@]}"; do
      [[ "$highlight" == "$ADAPTIVE_GHOST_HIGHLIGHT" ]] || kept+=("$highlight")
    done
    region_highlight=("${kept[@]}")
    ADAPTIVE_GHOST_HIGHLIGHT=""
  fi
}
_adaptive_set_ghost() {
  _adaptive_clear_ghost
  POSTDISPLAY="$1"
  if [[ -n "$POSTDISPLAY" ]]; then
    ADAPTIVE_GHOST_HIGHLIGHT="$#BUFFER $(( $#BUFFER + $#POSTDISPLAY )) $ADAPTIVE_GHOST_STYLE"
    region_highlight+=("$ADAPTIVE_GHOST_HIGHLIGHT")
  fi
}

_adaptive_clear() {
  _adaptive_clear_ghost
  if [[ -n "$ADAPTIVE_QUERY_FD" ]]; then
    zle -F "$ADAPTIVE_QUERY_FD" 2>/dev/null
    exec {ADAPTIVE_QUERY_FD}<&- 2>/dev/null
    ADAPTIVE_QUERY_FD=""
  fi
  if [[ "$ADAPTIVE_QUERY_PID" == <-> ]]; then
    kill "$ADAPTIVE_QUERY_PID" 2>/dev/null
    wait "$ADAPTIVE_QUERY_PID" 2>/dev/null
  fi
  ADAPTIVE_QUERY_PID=""
  ADAPTIVE_VALUES=(); ADAPTIVE_LABELS=(); ADAPTIVE_DESCRIPTIONS=(); ADAPTIVE_SOURCES=()
  zle -M "" 2>/dev/null
  zle -K main 2>/dev/null
}
_adaptive_render_menu() {
  local -a lines; local i marker
  for ((i=1; i<=${#ADAPTIVE_VALUES}; i++)); do
    marker="  "; (( i == ADAPTIVE_MENU_INDEX )) && marker="› "
    lines+=("${marker}[${i}] ${ADAPTIVE_LABELS[i]}  ${ADAPTIVE_DESCRIPTIONS[i]}")
  done
  zle -M "${(F)lines}"
}
_adaptive_should_menu() {
  [[ "$ADAPTIVE_MENU" == 1 ]] && (( ${#ADAPTIVE_VALUES} > 1 )) && [[ "${ADAPTIVE_SOURCES[1]}" == filesystem ]]
}
_adaptive_ready() {
  local fd=$1 header value label description source count request
  IFS=$'\t' read -r request ADAPTIVE_PREFIX_LEN count <&$fd
  ADAPTIVE_VALUES=(); ADAPTIVE_LABELS=(); ADAPTIVE_DESCRIPTIONS=(); ADAPTIVE_SOURCES=()
  while IFS=$'\t' read -r value label description source <&$fd; do
    ADAPTIVE_VALUES+=("$value"); ADAPTIVE_LABELS+=("$label"); ADAPTIVE_DESCRIPTIONS+=("$description"); ADAPTIVE_SOURCES+=("$source")
  done
  zle -F "$fd"; exec {fd}<&-; ADAPTIVE_QUERY_FD=""
  ADAPTIVE_QUERY_PID=""
  if [[ "$ADAPTIVE_GHOST_TEXT" == 1 ]] && (( ${#ADAPTIVE_VALUES} >= 1 )) && ! _adaptive_should_menu; then
    local current="" candidate="${ADAPTIVE_VALUES[1]}"
    (( ADAPTIVE_PREFIX_LEN > 0 )) && current="${LBUFFER[-$ADAPTIVE_PREFIX_LEN,-1]}"
    if [[ "$candidate" == "$current"* ]] && (( CURSOR == $#BUFFER )); then
      _adaptive_set_ghost "${candidate#$current}"
    fi
    zle -R
  elif _adaptive_should_menu; then ADAPTIVE_MENU_INDEX=1; zle -K adaptive-menu; _adaptive_render_menu
  else zle -M ""; zle -R
  fi
}
_adaptive_schedule() {
  _adaptive_clear
  exec {ADAPTIVE_QUERY_FD}< <(adaptive query --format zsh --buffer "$BUFFER" --cursor "$CURSOR" --cwd "$PWD" 2>/dev/null)
  ADAPTIVE_QUERY_PID=$!
  zle -F "$ADAPTIVE_QUERY_FD" _adaptive_ready
}
adaptive-self-insert() { zle .self-insert; _adaptive_schedule }
adaptive-backward-delete-char() { zle .backward-delete-char; _adaptive_schedule }
_adaptive_accept_selected() {
  (( ${#ADAPTIVE_VALUES} )) || return 1
  local keep=$(( ${#LBUFFER} - ADAPTIVE_PREFIX_LEN ))
  (( keep > 0 )) && LBUFFER="${LBUFFER[1,$keep]}" || LBUFFER=""
  LBUFFER+="${ADAPTIVE_VALUES[ADAPTIVE_MENU_INDEX]}"; _adaptive_clear; ADAPTIVE_VALUES=(); zle -M ""; zle -R
}
adaptive-menu-tab() { if ! _adaptive_accept_selected; then zle .expand-or-complete; fi }
adaptive-menu-up() { if (( ${#ADAPTIVE_VALUES} > 1 )); then (( ADAPTIVE_MENU_INDEX-- )); (( ADAPTIVE_MENU_INDEX < 1 )) && ADAPTIVE_MENU_INDEX=${#ADAPTIVE_VALUES}; _adaptive_render_menu; else zle .up-line-or-history; fi }
adaptive-menu-down() { if (( ${#ADAPTIVE_VALUES} > 1 )); then (( ADAPTIVE_MENU_INDEX++ )); (( ADAPTIVE_MENU_INDEX > ${#ADAPTIVE_VALUES} )) && ADAPTIVE_MENU_INDEX=1; _adaptive_render_menu; else zle .down-line-or-history; fi }
adaptive-menu-right() { if (( ${#ADAPTIVE_VALUES} > 1 )); then adaptive-menu-down; else zle .forward-char; fi }
adaptive-menu-number() { local index=$KEYS; if (( index >= 1 && index <= ${#ADAPTIVE_VALUES} )); then ADAPTIVE_MENU_INDEX=$index; _adaptive_accept_selected; else zle .self-insert; fi }
adaptive-menu-enter() { if [[ "${ADAPTIVE_ENTER_ACCEPTS_MENU:-0}" == 1 ]] && (( ${#ADAPTIVE_VALUES} > 1 )); then _adaptive_accept_selected; else _adaptive_clear; ADAPTIVE_VALUES=(); zle -M ""; zle .accept-line; fi }
adaptive-menu-escape() { _adaptive_clear; ADAPTIVE_VALUES=(); zle -M ""; zle -R }
_adaptive_history_hook() { adaptive history record -- "${1%$'\n'}" >/dev/null 2>&1 &!; return 0 }
zle -N self-insert adaptive-self-insert
zle -N backward-delete-char adaptive-backward-delete-char
zle -N adaptive-menu-tab adaptive-menu-tab
zle -N adaptive-menu-up adaptive-menu-up
zle -N adaptive-menu-down adaptive-menu-down
zle -N adaptive-menu-right adaptive-menu-right
zle -N adaptive-menu-number adaptive-menu-number
zle -N adaptive-menu-enter adaptive-menu-enter
zle -N adaptive-menu-escape adaptive-menu-escape
bindkey "$ADAPTIVE_ACCEPT_KEY" adaptive-menu-tab
bindkey "$ADAPTIVE_MENU_NEXT_KEY" adaptive-menu-right
bindkey -N adaptive-menu
bindkey -A main adaptive-menu
bindkey -M adaptive-menu '^I' adaptive-menu-tab
bindkey -M adaptive-menu '^[[A' adaptive-menu-up
bindkey -M adaptive-menu '^[[B' adaptive-menu-down
bindkey -M adaptive-menu '^M' adaptive-menu-enter
bindkey -M adaptive-menu '^[' adaptive-menu-escape
for _adaptive_number in {1..9}; do bindkey -M adaptive-menu "$_adaptive_number" adaptive-menu-number; done
autoload -Uz add-zsh-hook
add-zsh-hook zshaddhistory _adaptive_history_hook
